<table align="left">
  <td>
    <a href="https://colab.research.google.com/github/phonchi/CryoParticleSegment/blob/main/notebook/04_particle_extraction_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
  </td>
</table>

### CryoParticleSegment

In [ ]:
%pip install torchinfo -qq
%pip install -U git+https://github.com/qubvel/segmentation_models.pytorch -qq
%pip install starfile -qq
%pip install https://github.com/soft-matter/trackpy/archive/master.zip -qq

  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 121.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 96.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 60.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 40.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 18.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 110.9 MB/s eta 0:00:00
  Building wheel for segmentation_models_pytorch (pyproject.toml) ... done
     - 10.7 MB 10.0 MB/s 0:00:01
  Preparing metadata (setup.py) ... done
  Building wheel for trackpy (setup.py) ... done

> #### ⚠ Notice
>
> You need to restart the kernel after the following step.

In [ ]:
%pip install pycuda==2024.1
%pip install "numpy<2.0"
%pip install mrcfile -qq

Collecting pycuda==2024.1
  Downloading pycuda-2024.1.tar.gz (1.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 74.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pytools>=2011.2 (from pycuda==2024.1)
  Downloading pytools-2025.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting appdirs>=1.4.0 (from pycuda==2024.1)
  Downloading appdirs-1.4.4-py2.py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: mako in /usr/lib/python3/dist-packages (from pycuda==2024.1) (1.1.3)
Requirement already satisfied: platformdirs>=2.2 in /usr/local/lib/python3.11/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.3.8)
Collecting siphash24>=1.6 (from pytools>=2011.2->pycuda==2024.1)
  Downloading siphash24-1.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: typing-extensions>=4.5 in /usr/local/lib/python3.11/dist-packages (from pytools>=2011.2->pycuda==2024.1) (4.14.0)
Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Downloading pytools-2025.1.6-py3-none-any.whl (95 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.0/96.0 kB 10.5 MB/s eta 0:00:00
Downloading siphash24-1.7-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.6/105.6 kB 12.2 MB/s eta 0:00:00
Building wheels for collected packages: pycuda
  Building wheel for pycuda (pyproject.toml) ... done
  Created wheel for pycuda: filename=pycuda-2024.1-cp311-cp311-linux_x86_64.whl size=659519 sha256=07da3bbbc045b805626c6a74439cea5d08011ac718873c3e1d904b0a6274259f
  Stored in directory: /root/.cache/pip/wheels/9f/8c/1d/f9e11f5c0a8f91fd93b22ebf74c364ec59bc28bb2f76b2f64d
Successfully built pycuda
Installing collected packages: appdirs, siphash24, pytools, pycuda
Successfully installed appdirs-1.4.4 pycuda-2024.1 pytools-2025.1.6 siphash24-1.7
Collecting numpy<2.0
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.2 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 95.7 MB/s eta 0:00:00
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 4.0 MB/s eta 0:00:00
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/base_command.py", line 179, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
^C

## ⭐ Setup
You must run all codes under this category.

### ✅ Directory Settings

In [1]:
# @title  { display-mode: "form" }

IMAGE_DIR = "/content/drive/MyDrive/research_xc/dataset/10017/processed_micrographs_np_split" # @param {type:"string"}
LABEL_DIR = "/content/drive/MyDrive/research_xc/dataset/10017/micrographs_ground_np" # @param {type:"string"}
DATASET_DIR = "/content/drive/MyDrive/research_xc/dataset" # @param {type:"string"}
RESULT_DIR = "/content/drive/MyDrive/research_xc/results/10017_test/unet_eb5_dice_CDCRF" # @param {type:"string"}

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# @title  { display-mode: "form" }
# @markdown Detect whether using folder in Google Drive as **`RESULT DIR`**📁.
import os
if "content" in IMAGE_DIR.split("/")[:3] or "content" in LABEL_DIR.split("/")[:3]:
  try:
    from google.colab import drive
    drive.mount('/content/drive')
    !rm -r /content/sample_data
    if not os.path.exists("/content/image_dir"):
        if "content" in IMAGE_DIR.split("/")[:3]:
            !cp -r {IMAGE_DIR} /content/image_dir
            IMAGE_DIR = "/content/image_dir"
        if "content" in LABEL_DIR.split("/")[:3]:
            !cp -r {LABEL_DIR} /content/label_dir
            LABEL_DIR = "/content/label_dir"
  except:
    pass

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
rm: cannot remove '/content/sample_data': No such file or directory

In [2]:
IMAGE_DIR = "/content/image_dir"

In [ ]:
!git clone https://github.com/phonchi/CryoParticleSegment.git

Cloning into 'CryoParticleSegment'...
remote: Enumerating objects: 195, done.
remote: Counting objects: 100% (195/195), done.
remote: Compressing objects: 100% (185/185), done.
remote: Total 195 (delta 90), reused 27 (delta 6), pack-reused 0 (from 0)
Receiving objects: 100% (195/195), 29.46 MiB | 12.55 MiB/s, done.
Resolving deltas: 100% (90/90), done.

In [3]:
import sys
import os

# Adjust the path relative to your current working directory
module_path = os.path.abspath('CryoParticleSegment/Modeling')

# Add to sys.path if it's not already included
if module_path not in sys.path:
    sys.path.append(module_path)

> #### ⚠ Notice
>
> You need to restart the kernel after the compilation step. Additionally, if your GPU architecture differs, you may need to modify the file at `/content/CryoParticleSegment/Modeling/CRF_main/setup.py`. (We attempt to detect the GPU configuration automatically, so this step is usually not necessary.)
> Furthermore, depending on the number of classes and other parameters, you may encounter an error that requires adjusting the file at `/content/CryoParticleSegment/Modeling/CRF_main/src/PermutohedralFiltering/source/gpu/LatticeFilter.cu`:
>
> 1. Note the `pd` and `vd` values from the error message.
> 2. Add an `else if (pd == ? && vd == ?)` block.
> 3. Within that block, insert the following line, replacing `pd` and `vd` with the specific values:
>
>    ```cpp
>    latticeFilterGPU<pd, vd>(output_tensor, input_tensor, positions, num_super_pixels, backward);
>    ```
> 4. Recompile using `setup.py`.

In [ ]:
#%git clone https://github.com/netw0rkf10w/CRF.git
%cd CryoParticleSegment/Modeling/CRF_main
!python setup.py clean --all
!rm -rf build/
!python setup.py build_ext --inplace --force
!python setup.py install

/content/CryoParticleSegment/Modeling/CRF_main
running clean
'build/lib.linux-x86_64-cpython-311' does not exist -- can't clean it
'build/bdist.linux-x86_64' does not exist -- can't clean it
'build/scripts-3.11' does not exist -- can't clean it
running build_ext
/usr/local/lib/python3.11/dist-packages/torch/utils/cpp_extension.py:529: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
/usr/local/lib/python3.11/dist-packages/torch/utils/cpp_extension.py:448: UserWarning: The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.4). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
/usr/local/lib/python3.11/dist-packages/torch/utils/cpp_extension.py:458: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
building 'Permutohedral' extension
creating build/temp.linux-x86_64-cpython-311/src/PermutohedralFiltering/source/cpu
x86_64-linux-gnu-g++ -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/local/lib/python3.11/dist-packages/torch/include -I/usr/local/lib/python3.11/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.11/dist-packages/torch/include/TH -I/usr/local/lib/python3.11/dist-packages/torch/include/THC -I/usr/include/python3.11 -c src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp -o build/temp.linux-x86_64-cpython-311/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=Permutohedral -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp: In function ‘at::Tensor LatticeFilter_calculate(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool)’:
src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:77:97: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
   77 |         at::Tensor positions = at::zeros({batch_size * num_super_pixels * pd}, input_tensor.type() );
      |                                                                                ~~~~~~~~~~~~~~~~~^~
In file included from /usr/local/lib/python3.11/dist-packages/torch/include/ATen/core/Tensor.h:3,
                 from /usr/local/lib/python3.11/dist-packages/torch/include/ATen/Tensor.h:3,
                 from /usr/local/lib/python3.11/dist-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                 from /usr/local/lib/python3.11/dist-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                 from /usr/local/lib/python3.11/dist-packages/torch/include/torch/csrc/autograd/variable.h:6,
                 from /usr/local/lib/python3.11/dist-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                 from /usr/local/lib/python3.11/dist-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                 from /usr/local/lib/python3.11/dist-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                 from /usr/local/lib/python3.11/dist-packages/torch/include/torch/extension.h:5,
                 from src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.cpp:25:
/usr/local/lib/python3.11/dist-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
creating build/lib.linux-x86_64-cpython-311
x86_64-linux-gnu-g++ -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions build/temp.linux-x86_64-cpython-311/src/PermutohedralFiltering/source/cpu/LatticeFilterKernel.o -L/usr/local/lib/python3.11/dist-packages/torch/lib -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -o build/lib.linux-x86_64-cpython-311/Permutohedral.cpython-311-x86_64-linux-gnu.so
building 'Permutohedral_gpu' extension
creating build/temp.linux-x86_64-cpython-311/src/PermutohedralFiltering/source/gpu
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.11/dist-packages/torch/include -I/usr/local/lib/python3.11/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.11/dist-packages/torch/include/TH -I/usr/local/lib/python3.11/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.11 -c src/PermutohedralFiltering/source/gpu/LatticeFilter.cu -o build/temp.linux-x86_64-cpython-311/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -gencode=arch=compute_89,code=sm_89 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -DTORCH_EXTENSION_NAME=Permutohedral_gpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++17
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu: In function ‘at::Tensor LatticeFilter_calculate_gpu(const at::Tensor&, const at::Tensor&, bool, float, float, float, bool, bool)’:
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:202:91: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  202 |     at::Tensor positions = at::zeros(
      |                                                                                           ^
/usr/local/lib/python3.11/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:208:67: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  208 |     CHECK_INPUT(image_tensor);
      |                                                                   ^
/usr/local/lib/python3.11/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:209:64: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  209 |     CHECK_INPUT(positions);
      |                                                                ^
/usr/local/lib/python3.11/dist-packages/torch/include/ATen/core/TensorBody.h:225:1: note: declared here
  225 |   DeprecatedTypeProperties & type() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:213:44: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  213 |         auto ref_ptr = &(image_tensor.data<float>()[b * num_super_pixels * n_reference_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.11/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:214:41: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  214 |         auto pos_ptr = &(positions.data<float>()[b * num_super_pixels * pd]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.11/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:215:43: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  215 |         auto in_ptr = &(input_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.11/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
src/PermutohedralFiltering/source/gpu/LatticeFilter.cu:216:45: warning: ‘T* at::Tensor::data() const [with T = float]’ is deprecated: Tensor.data<T>() is deprecated. Please use Tensor.data_ptr<T>() instead. []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wdeprecated-declarations-Wdeprecated-declarations]8;;]
  216 |         auto out_ptr = &(output_tensor.data<float>()[b * num_super_pixels * n_input_channels]);
      |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
/usr/local/lib/python3.11/dist-packages/torch/include/ATen/core/TensorBody.h:247:1: note: declared here
  247 |   T * data() const {
      | ^ ~~
x86_64-linux-gnu-g++ -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -shared -Wl,-O1 -Wl,-Bsymbolic-functions build/temp.linux-x86_64-cpython-311/src/PermutohedralFiltering/source/gpu/LatticeFilter.o -L/usr/local/lib/python3.11/dist-packages/torch/lib -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda -o build/lib.linux-x86_64-cpython-311/Permutohedral_gpu.cpython-311-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-cpython-311/Permutohedral.cpython-311-x86_64-linux-gnu.so -> src
copying build/lib.linux-x86_64-cpython-311/Permutohedral_gpu.cpython-311-x86_64-linux-gnu.so -> src
running install
/usr/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/usr/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
running bdist_egg
running egg_info
creating src/CRF.egg-info
writing src/CRF.egg-info/PKG-INFO
writing dependency_links to src/CRF.egg-info/dependency_links.txt
writing top-level names to src/CRF.egg-info/top_level.txt
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
/usr/local/lib/python3.11/dist-packages/torch/utils/cpp_extension.py:529: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'src/CRF.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'src/CRF.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/lib.linux-x86_64-cpython-311/PermutohedralFiltering
copying src/PermutohedralFiltering/PermutohedralFiltering.py -> build/lib.linux-x86_64-cpython-311/PermutohedralFiltering
copying src/PermutohedralFiltering/__init__.py -> build/lib.linux-x86_64-cpython-311/PermutohedralFiltering
copying src/PermutohedralFiltering/setup.py -> build/lib.linux-x86_64-cpython-311/PermutohedralFiltering
creating build/lib.linux-x86_64-cpython-311/CRF
copying src/CRF/crfs_cpu.py -> build/lib.linux-x86_64-cpython-311/CRF
copying src/CRF/__init__.py -> build/lib.linux-x86_64-cpython-311/CRF
copying src/CRF/convcrf.py -> build/lib.linux-x86_64-cpython-311/CRF
copying src/CRF/CRF.py -> build/lib.linux-x86_64-cpython-311/CRF
copying src/CRF/sparsemax.py -> build/lib.linux-x86_64-cpython-311/CRF
running build_ext
/usr/local/lib/python3.11/dist-packages/torch/utils/cpp_extension.py:448: UserWarning: The detected CUDA version (12.5) has a minor version mismatch with the version that was used to compile PyTorch (12.4). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
/usr/local/lib/python3.11/dist-packages/torch/utils/cpp_extension.py:458: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.5
  warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-cpython-311/Permutohedral_gpu.cpython-311-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-311/PermutohedralFiltering/PermutohedralFiltering.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-311/PermutohedralFiltering/__init__.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-311/PermutohedralFiltering/setup.py -> build/bdist.linux-x86_64/egg/PermutohedralFiltering
copying build/lib.linux-x86_64-cpython-311/Permutohedral.cpython-311-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-311/CRF/crfs_cpu.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-311/CRF/__init__.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-311/CRF/convcrf.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-311/CRF/CRF.py -> build/bdist.linux-x86_64/egg/CRF
copying build/lib.linux-x86_64-cpython-311/CRF/sparsemax.py -> build/bdist.linux-x86_64/egg/CRF
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/PermutohedralFiltering.py to PermutohedralFiltering.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/PermutohedralFiltering/setup.py to setup.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/crfs_cpu.py to crfs_cpu.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/convcrf.py to convcrf.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/CRF.py to CRF.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/CRF/sparsemax.py to sparsemax.cpython-311.pyc
creating stub loader for Permutohedral.cpython-311-x86_64-linux-gnu.so
creating stub loader for Permutohedral_gpu.cpython-311-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral.py to Permutohedral.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/Permutohedral_gpu.py to Permutohedral_gpu.cpython-311.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying src/CRF.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
CRF.__pycache__.crfs_cpu.cpython-311: module references __file__
__pycache__.Permutohedral.cpython-311: module references __file__
__pycache__.Permutohedral_gpu.cpython-311: module references __file__
creating dist
creating 'dist/CRF-0.0.1-py3.11-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing CRF-0.0.1-py3.11-linux-x86_64.egg
creating /usr/local/lib/python3.11/dist-packages/CRF-0.0.1-py3.11-linux-x86_64.egg
Extracting CRF-0.0.1-py3.11-linux-x86_64.egg to /usr/local/lib/python3.11/dist-packages
Adding CRF 0.0.1 to easy-install.pth file

Installed /usr/local/lib/python3.11/dist-packages/CRF-0.0.1-py3.11-linux-x86_64.egg
Processing dependencies for CRF==0.0.1
Finished processing dependencies for CRF==0.0.1

In [4]:
%cd /content/

/content

### ✅ Packages Handling

In [5]:
# @title  { display-mode: "form" }
# @markdown Useful packages.

import os
import numpy as np
import matplotlib.pyplot as plt
import torch
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import ReduceLROnPlateau, OneCycleLR

In [6]:
# @title  { display-mode: "form" }
# @markdown User-defined packages.

from dataset import MicrographDataset, MicrographDatasetEvery
from dataset import reconstruct_patched
from model import create_model
from trainer import CryoEMEvaluator
from trainer import CryoEMTrainerWithScheduler, tqdm_plugin_for_Trainer

## ⭐ Main

### ✅ Setting

In [7]:
# @markdown Parameters.

NUM_CLASSES = 2
EPOCHS = 50
BATCH = 2
CROP_SIZE = (512, 512)
LR = 1e-3

RLR_PATIENCE = 3
ES_PATIENCE = 15
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [8]:
# @markdown Set seed.

random_state = 42
torch.manual_seed(random_state)
torch.cuda.manual_seed_all(random_state)

## ⭐ Convcrf wtih FCN finetuned on cryoem

### ✅ Model

## The model

In [9]:
# @title  { display-mode: "form" }

architecture = "Unet++" # @param {type:"string"}
encoder = "timm-efficientnet-b5" # @param {type:"string"}
pretrained = True # @param {type:"boolean"}
solver = "fw" # @param {type:"string"}
use_unary_only = True # @param {type:"boolean"}

In [10]:
import segmentation_models_pytorch as smp

if pretrained:
  weights = "imagenet"
else:
  weights = None

if architecture == "Unet++":
    backbone = smp.UnetPlusPlus(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` or `advprop` for pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )

elif architecture == "Deeplab":
    backbone = smp.DeepLabV3(
        encoder_name=encoder,        # choose encoder, densenet201, resnet50, e.g. mobilenet_v2 or efficientnet-b5
        encoder_weights=weights,     # use `imagenet` pre-trained weights for encoder initialization
        in_channels=1,                  # model input channels (1 for gray-scale images, 3 for RGB, etc.)
        classes=2,                      # model output channels (number of classes in your dataset)
    )
else:
    print("Architecture not supported")
    raise NotImplementedError

model = create_model(backbone, addout=True) #crf_args

In [11]:
import CRF
import torch.nn as nn
from model import setup_crf, create_fwcrf_model

# Example usage
solver = 'fw'  # Assuming the solver type is defined

crf = setup_crf(solver, NUM_CLASSES)
model_post = create_fwcrf_model(model.backbone, crf, use_unary_only=True)

CRF solver: fw
x0_weight: 0.0
FrankWolfeParams:
	 scheme:	 fixed
	 stepsize:	 1.0 (for the 'fixed' scheme)
	 regularizer:	 l2
	 lambda_:	 1.0
	 lambda_learnable:	 False
	 x0_weight:	 0.5
	 x0_weight_learnable:	 False
Non-trainable lambda for Frank-Wolfe: 1.0
Non-trainable x0_weight for Frank-Wolfe: 0.5
Potts: remove random weights.
Add 1.0 to spatial_weight diagonal
Add 1.0 to bilateral_weight diagonal
Add -1.0 to compatibility diagonal

## ⭐ Evaluate

In [12]:
import gc
gc.collect()
torch.cuda.empty_cache()

from torchvision.utils import save_image
from dataset import reconstruct_patched

def simple_micrograph_preprocessing(micrograph):
  micrograph_copy = micrograph.copy()
  micrograph_copy = (micrograph_copy-micrograph.mean()+2.5*micrograph.std())/5/micrograph.std()
  micrograph_copy[micrograph_copy<0]=0
  micrograph_copy[micrograph_copy>1]=1
  return micrograph_copy

In [17]:
from torch.utils.data import ConcatDataset

train_dir = os.path.join(IMAGE_DIR, 'train')
train_filenames = np.loadtxt(f"{IMAGE_DIR}/train_filenames.txt", dtype=str)
train_dataset =  MicrographDatasetEvery(image_dir=train_dir, label_dir=LABEL_DIR, filenames=train_filenames, crop_size=CROP_SIZE)
train_loader = DataLoader(train_dataset , batch_size=None, shuffle=False, pin_memory=True)

val_dir = os.path.join(IMAGE_DIR, 'val')
val_filenames = np.loadtxt(f"{IMAGE_DIR}/val_filenames.txt", dtype=str)
val_dataset = MicrographDatasetEvery(image_dir=val_dir, label_dir=LABEL_DIR, filenames=val_filenames, crop_size=CROP_SIZE)
val_loader = DataLoader(val_dataset, batch_size=None, shuffle=False, pin_memory=True)

test_dir = os.path.join(IMAGE_DIR, 'test')
test_filenames = np.loadtxt(f"{IMAGE_DIR}/test_filenames.txt", dtype=str)
test_dataset = MicrographDatasetEvery(image_dir=test_dir, label_dir=None, filenames=test_filenames, crop_size=CROP_SIZE)
test_loader = DataLoader(test_dataset, batch_size=None, shuffle=False, pin_memory=True)

full_filenames = np.concatenate((train_filenames, val_filenames, test_filenames))
full_dataset = ConcatDataset([train_dataset, val_dataset, test_dataset])
full_loader = DataLoader(full_dataset, batch_size=32, shuffle=True, pin_memory=True)

In [18]:
shape = None
for i1, i2, i3, i4 in val_loader: #test loader and reconstruct
    shape = i4.shape
    break

In [19]:
from PIL import Image

def normalize(im):
    max_mrc=np.max(im)
    min_mrc=np.min(im)
    img_original=(255*((im-min_mrc)/(max_mrc-min_mrc))).astype(np.uint8)
    return(img_original)

def preprocess_and_crop(micrograph, crop_size=3840):
    processed_micrograph = simple_micrograph_preprocessing(micrograph)
    if crop_size:
        mic_width, mic_height = processed_micrograph.shape[1], processed_micrograph.shape[0]
        start_x, start_y = (mic_width - crop_size) // 2, (mic_height - crop_size) // 2
        end_x, end_y = start_x + crop_size, start_y + crop_size
        return processed_micrograph[start_y:end_y, start_x:end_x]
    else:
        return processed_micrograph

In [20]:
from tqdm import tqdm

fnames = []
n = len(full_dataset)
processed_micrographs = np.empty((n, shape[1], shape[2]), dtype=np.float32)

# Use tqdm to wrap your loop for a progress bar
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing images"):
    name = full_filenames[idx][:-4]
    fnames.append(name)
    # Determine the directory and load the micrograph
    if os.path.exists(f"{IMAGE_DIR}/test/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/test/{name}.npy"
    elif os.path.exists(f"{IMAGE_DIR}/train/{name}.npy"):
        micrograph_path = f"{IMAGE_DIR}/train/{name}.npy"
    else:
        micrograph_path = f"{IMAGE_DIR}/val/{name}.npy"
    micrograph = np.load(micrograph_path)
    processed_micrograph = preprocess_and_crop(micrograph)
    # Place the processed micrograph directly into the preallocated array
    processed_micrographs[idx] = processed_micrograph

Processing images: 100%|██████████| 84/84 [00:36<00:00,  2.31it/s]

In [21]:
processed_micrographs.shape

(84, 3840, 3840)

In [22]:
np.save(f"{RESULT_DIR}/processed_micrographs.npy", processed_micrographs)

In [ ]:
processed_micrographs = np.load(f"{RESULT_DIR}/processed_micrographs.npy")

In [23]:
del model
torch.cuda.empty_cache()

In [24]:
model = model_post

In [25]:
RESULT_DIR

'/content/drive/MyDrive/research_xc/results/10017_test/unet_eb5_dice_CDCRF'

In [26]:
import torch.nn.functional as F

label_images = np.empty((0, shape[1], shape[2]), dtype=np.uint8)

checkpoint_paths = [path for path in os.listdir(RESULT_DIR) if '.pt' in path]
checkpoint_path = checkpoint_paths[-1]
state_dict_path = f"{RESULT_DIR}/{checkpoint_path}"
state_dict = torch.load(state_dict_path, map_location=torch.device(device))
model.load_state_dict(state_dict, strict=False)

model.to(device)
model.eval()

mini_batch_size = 18  # Number of patches to process at once
n = len(full_dataset)
label_images = np.empty((n, shape[1], shape[2]), dtype=np.uint8)  # Preallocated array

# Iterate through the dataset with tqdm for progress tracking
for idx, (test_image, _, grid, _) in tqdm(enumerate(full_dataset), total=n, desc="Processing dataset"):
    # Process in batches
    with torch.no_grad():
        inputs = test_image.to(device)
        num_batches = (inputs.size(0) + mini_batch_size - 1) // mini_batch_size
        patched_outputs = []

        for batch_idx in range(num_batches):
            start_idx = batch_idx * mini_batch_size
            end_idx = min(start_idx + mini_batch_size, inputs.size(0))
            patch_input = inputs[start_idx:end_idx].to(device)
            output = model(patch_input)['out']
            patched_outputs.append(output.cpu())  # Minimize device memory usage

            # Cleanup as soon as not needed
            del patch_input, output
            torch.cuda.empty_cache()

        outputs = torch.cat(patched_outputs)  # Combine outputs
        probabilities = F.softmax(outputs, dim=1)
        class1_probabilities = probabilities[:, 1, :, :]  # Assuming class 1 is the target
        pred_image = reconstruct_patched(class1_probabilities.unsqueeze(1), grid).float()
        output_image = normalize(pred_image.squeeze().numpy())

        # Cleanup large temporary variables
        del patched_outputs, outputs, probabilities, class1_probabilities, pred_image
        torch.cuda.empty_cache()

    # Store the output image directly in the preallocated array
    label_images[idx] = output_image

    if idx % 30 == 0:
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(output_image, cmap='inferno', alpha=0.4)
        plt.show()
    del output_image
    torch.cuda.empty_cache()

Output hidden; open in https://colab.research.google.com to view.

In [27]:
np.save(f"{RESULT_DIR}/label_images.npy", label_images)

In [ ]:
!cp {RESULT_DIR}/label_images.npy .

In [ ]:
label_images = np.load(f"{RESULT_DIR}/label_images.npy")

In [28]:
label_images.shape

(84, 3840, 3840)

In [29]:
# @title  { vertical-output: true, display-mode: "form" }
EMPIAR_ID = 10017 # @param {type:"integer"}
RADIUS = 64 # @param {type:"integer"}
# For 10017
BORDER = 128 # @param {type:"integer"}

In [30]:
!cp {RESULT_DIR}/best_config.txt .

In [31]:
with open("best_config.txt", "r") as f:
    for line in f:
        key, value = line.strip().split(": ", 1)
        if key == "cv_config":
            cv_config = eval(value)
        elif key == "tp_config":
            tp_config = eval(value)
        elif key == "nms_config":
            nms_config = eval(value)

### Actual seg

In [33]:
radius = RADIUS

In [37]:
from skimage import filters, segmentation, morphology
import skimage as ski
from skimage import img_as_float
from center_finding import normalize, min_rect_circle, eliminate_near
import cv2

In [39]:
from skimage import img_as_float
from skimage.filters import threshold_local

cv_list = []
for img in label_images:
    output_image = img_as_float(img)
    block_size = int(round(radius * 1.6)) | 1  # Ensure it's an odd number
    local_thresh = filters.threshold_local(output_image, block_size, method='gaussian', offset=0)
    image_seg = output_image > local_thresh
    thresh1 = ski.util.img_as_ubyte(image_seg)

    contr_min = radius*cv_config[1]
    kernel_size = int(radius / cv_config[0])  # Example ratio
    kernel = np.ones((kernel_size, kernel_size), np.uint8)
    thresh1 = cv2.erode(thresh1, kernel, iterations=1)

    contours, hierarchy = cv2.findContours(thresh1,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_SIMPLE)
    cont_array = [c for c in contours]

    # Filter out small/large region and find bounding box with center
    c_ = np.array([cv2.contourArea(contour) for contour in contours])
    aa = (c_>contr_min) & (c_<500000)
    aa = aa.tolist()
    c_full_list = [d for d, keep in zip(cont_array, aa) if keep]
    c_list = (list(map(lambda x: min_rect_circle(x, radius), c_full_list)))
    c_list = [x for x in c_list if x is not None]
    cv_list.append(c_list)
    print(len(c_full_list), len(c_list))

573 564
611 596
626 613
545 530
527 514
597 580
603 582
593 570
568 556
575 552
620 598
645 630
580 571
658 632
577 568
523 515
633 625
623 616
570 542
563 545
555 548
614 587
606 593
592 579
607 567
360 360
350 349
399 390
450 442
422 419
404 402
658 624
579 568
606 590
585 572
614 599
582 561
608 588
474 471
581 570
542 531
629 616
568 559
608 587
486 469
396 386
390 386
404 403
398 393
407 401
409 407
565 553
579 565
583 575
594 582
574 567
570 568
492 488
474 471
394 394
365 364
433 425
452 442
440 430
439 430
496 487
488 478
460 459
469 454
460 453
500 494
475 465
492 477
438 422
486 469
430 418
644 632
633 622
545 543
475 467
557 548
465 454
582 544
435 428

In [40]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    #if idx == 6:
    #    break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in cv_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [41]:
!pip install starfile -qq

DEPRECATION: Loading egg at /usr/local/lib/python3.11/dist-packages/CRF-0.0.1-py3.11-linux-x86_64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

In [42]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in cv_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [43]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,3302,3938,00000@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
1,1044,3937,00001@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
2,1857,3931,00002@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
3,574,3927,00003@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
4,3475,3910,00004@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
...,...,...,...,...
43179,296,230,00423@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
43180,1389,161,00424@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
43181,907,167,00425@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
43182,1258,174,00426@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
43183,3116,166,00427@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc

In [45]:
import starfile
starfile.write(df, f'{RESULT_DIR}/cv_particles.star')

### TrackPy

In [60]:
cv_list

[[(3174, 3810),
  (916, 3809),
  (1729, 3803),
  (446, 3799),
  (3347, 3782),
  (2084, 3783),
  (3617, 3788),
  (1144, 3784),
  (1059, 3781),
  (3496, 3784),
  (2720, 3757),
  (94, 3747),
  (1642, 3750),
  (2543, 3737),
  (1729, 3731),
  (1941, 3715),
  (3796, 3672),
  (2090, 3669),
  (490, 3652),
  (668, 3649),
  (2694, 3654),
  (1042, 3656),
  (2876, 3652),
  (1631, 3643),
  (3033, 3628),
  (3508, 3629),
  (3324, 3618),
  (2942, 3667),
  (401, 3619),
  (2547, 3595),
  (3720, 3574),
  (2430, 3585),
  (2646, 3569),
  (558, 3583),
  (993, 3568),
  (1931, 3564),
  (3153, 3556),
  (1410, 3596),
  (1552, 3521),
  (3391, 3524),
  (3468, 3510),
  (2292, 3509),
  (901, 3503),
  (594, 3505),
  (156, 3534),
  (357, 3481),
  (3612, 3463),
  (1251, 3478),
  (3813, 3459),
  (1377, 3465),
  (1977, 3464),
  (237, 3462),
  (3320, 3457),
  (2455, 3455),
  (1457, 3429),
  (1736, 3443),
  (2572, 3422),
  (836, 3404),
  (447, 3416),
  (1868, 3416),
  (2923, 3415),
  (1142, 3404),
  (981, 3386),
  (2376, 3369),
  (1327, 3371),
  (3080, 3359),
  (2857, 3358),
  (1819, 3361),
  (596, 3357),
  (3209, 3343),
  (278, 3362),
  (768, 3350),
  (2027, 3326),
  (3563, 3340),
  (2225, 3358),
  (2523, 3326),
  (1065, 3320),
  (2946, 3313),
  (1679, 3302),
  (2631, 3292),
  (714, 3293),
  (3623, 3277),
  (3202, 3264),
  (3089, 3268),
  (3756, 3270),
  (1772, 3260),
  (962, 3248),
  (226, 3252),
  (378, 3294),
  (1168, 3246),
  (1058, 3239),
  (1576, 3278),
  (3314, 3222),
  (2979, 3226),
  (1915, 3210),
  (2601, 3203),
  (2793, 3198),
  (1382, 3185),
  (958, 3179),
  (3207, 3174),
  (422, 3185),
  (3109, 3164),
  (600, 3159),
  (1818, 3167),
  (2706, 3159),
  (337, 3135),
  (3503, 3130),
  (1918, 3127),
  (104, 3122),
  (723, 3123),
  (3646, 3103),
  (1370, 3084),
  (3755, 3085),
  (3248, 3091),
  (589, 3073),
  (899, 3071),
  (262, 3072),
  (1606, 3067),
  (3467, 3044),
  (1897, 3037),
  (2155, 3041),
  (1456, 3050),
  (1088, 3018),
  (2274, 3000),
  (3609, 3004),
  (403, 3023),
  (307, 2962),
  (1339, 2972),
  (725, 2964),
  (581, 2963),
  (818, 2950),
  (2832, 2979),
  (2178, 2950),
  (3738, 2945),
  (2673, 2925),
  (1078, 2924),
  (1709, 2928),
  (1811, 2925),
  (1181, 2920),
  (3202, 2903),
  (2084, 2924),
  (1970, 2902),
  (2952, 2893),
  (705, 2876),
  (3574, 2862),
  (3053, 2876),
  (1439, 2846),
  (467, 2849),
  (905, 2834),
  (3718, 2823),
  (1309, 2800),
  (261, 2809),
  (2989, 2799),
  (3383, 2788),
  (846, 2779),
  (520, 2757),
  (336, 2770),
  (431, 2776),
  (2433, 2768),
  (3630, 2756),
  (697, 2761),
  (1380, 2753),
  (2217, 2744),
  (966, 2740),
  (2932, 2736),
  (3522, 2718),
  (2517, 2707),
  (1249, 2719),
  (1125, 2710),
  (1787, 2708),
  (3391, 2700),
  (1454, 2699),
  (769, 2695),
  (1937, 2727),
  (2719, 2695),
  (3190, 2687),
  (3704, 2674),
  (2643, 2674),
  (1696, 2662),
  (3323, 2627),
  (2549, 2613),
  (959, 2616),
  (3447, 2612),
  (2980, 2618),
  (2013, 2606),
  (2637, 2591),
  (85, 2588),
  (287, 2587),
  (2281, 2553),
  (1834, 2561),
  (1716, 2546),
  (1429, 2535),
  (560, 2523),
  (2216, 2527),
  (3698, 2539),
  (3319, 2521),
  (3790, 2504),
  (785, 2514),
  (122, 2498),
  (3215, 2498),
  (695, 2495),
  (1618, 2503),
  (1768, 2479),
  (407, 2469),
  (3433, 2458),
  (2568, 2465),
  (1866, 2465),
  (281, 2462),
  (3669, 2464),
  (2483, 2445),
  (529, 2409),
  (1235, 2417),
  (2807, 2448),
  (2131, 2433),
  (2293, 2416),
  (3582, 2393),
  (1093, 2384),
  (1812, 2386),
  (3725, 2391),
  (3297, 2391),
  (1620, 2382),
  (1994, 2372),
  (1000, 2353),
  (1299, 2345),
  (606, 2350),
  (2115, 2333),
  (193, 2332),
  (1484, 2353),
  (301, 2325),
  (3446, 2325),
  (2348, 2319),
  (1812, 2295),
  (426, 2311),
  (3800, 2294),
  (2863, 2282),
  (3367, 2277),
  (528, 2270),
  (1116, 2254),
  (3237, 2257),
  (1877, 2262),
  (115, 2261),
  (1532, 2242),
  (659, 2241),
  (2584, 2231),
  (875, 2227),
  (1223, 2225),
  (2307, 2224),
  (2966, 2206),
  (3767, 2213),
  (2132, 2186),
  (3402, 2171),
  (2775, 2166),
  (1969, 2156),
  (702, 2164),
  (1676, 2145),
  (838, 2154),
  (1126, 2148),
  (2867, 2135),
  (3613, 2124),
  (996, 2121),
  (3018, 2129),
  (2090, 2103),
  (2694, 2087),
  (3332, 2068),
  (2595, 2076),
  (2188, 2071),
  (1827, 2064),
  (1326, 2063),
  (123, 2050),
  (2289, 2035),
  (2874, 2026),
  (1577, 2042),
  (1111, 2008),
  (1959, 2017),
  (1662, 2021),
  (774, 2012),
  (3792, 2011),
  (3379, 2012),
  (2498, 1999),
  (3150, 1985),
  (3263, 1990),
  (899, 2006),
  (2715, 1935),
  (1230, 1946),
  (415, 1927),
  (2532, 1932),
  (3507, 1915),
  (3425, 1948),
  (1535, 1902),
  (307, 1889),
  (708, 1909),
  (206, 1893),
  (958, 1871),
  (3349, 1866),
  (2392, 1868),
  (2693, 1855),
  (1409, 1850),
  (1085, 1848),
  (1246, 1830),
  (2242, 1843),
  (3719, 1831),
  (400, 1824),
  (141, 1810),
  (1633, 1791),
  (740, 1800),
  (2484, 1786),
  (2679, 1769),
  (3105, 1776),
  (1433, 1760),
  (219, 1758),
  (472, 1740),
  (1946, 1730),
  (1037, 1731),
  (756, 1720),
  (2371, 1737),
  (3806, 1710),
  (856, 1715),
  (1813, 1749),
  (2216, 1726),
  (2460, 1710),
  (3305, 1715),
  (2947, 1693),
  (1665, 1690),
  (3471, 1666),
  (108, 1641),
  (3164, 1633),
  (623, 1677),
  (2072, 1613),
  (3251, 1623),
  (2572, 1613),
  (1382, 1606),
  (844, 1597),
  (3429, 1597),
  (3049, 1580),
  (253, 1590),
  (1195, 1559),
  (1862, 1562),
  (994, 1556),
  (1080, 1555),
  (1595, 1550),
  (47, 1547),
  (3175, 1534),
  (1439, 1523),
  (2001, 1529),
  (467, 1524),
  (895, 1526),
  (350, 1516),
  (2440, 1487),
  (3775, 1499),
  (992, 1482),
  (1698, 1474),
  (3429, 1464),
  (1096, 1444),
  (270, 1446),
  (3030, 1450),
  (2899, 1454),
  (1346, 1445),
  (2656, 1428),
  (1540, 1429),
  (2533, 1469),
  (872, 1412),
  (2138, 1409),
  (1225, 1407),
  (3312, 1405),
  (1450, 1401),
  (1814, 1424),
  (1001, 1382),
  (3603, 1359),
  (2397, 1355),
  (1326, 1358),
  (2964, 1357),
  (2822, 1338),
  (3439, 1332),
  (3748, 1339),
  (2636, 1331),
  (3093, 1335),
  (152, 1326),
  (3351, 1333),
  (363, 1326),
  (455, 1309),
  (2335, 1294),
  (3693, 1300),
  (2251, 1298),
  (2511, 1303),
  (1615, 1274),
  (1928, 1270),
  (805, 1264),
  (3030, 1260),
  (1332, 1254),
  (136, 1236),
  (1877, 1222),
  (2054, 1211),
  (1134, 1205),
  (2128, 1187),
  (1790, 1184),
  (2507, 1176),
  (1649, 1170),
  (400, 1173),
  (2703, 1176),
  (2424, 1163),
  (2978, 1141),
  (74, 1138),
  (2834, 1134),
  (214, 1134),
  (2665, 1119),
  (1982, 1109),
  (920, 1119),
  (2371, 1107),
  (3435, 1148),
  (3137, 1096),
  (3561, 1097),
  (2267, 1072),
  (736, 1115),
  (3668, 1071),
  (1894, 1044),
  (582, 1055),
  (2589, 1066),
  (3118, 1010),
  (350, 1017),
  (1226, 991),
  (1792, 992),
  (451, 983),
  (248, 987),
  (3236, 967),
  (2279, 968),
  (1337, 1017),
  (1886, 964),
  (2772, 955),
  (1622, 966),
  (3320, 967),
  (1984, 951),
  (2901, 948),
  (31, 936),
  (911, 937),
  (3168, 926),
  (2492, 934),
  (1766, 918),
  (3537, 939),
  (401, 900),
  (1052, 890),
  (1965, 868),
  (3002, 876),
  (2543, 852),
  (1320, 848),
  (3457, 847),
  (2845, 842),
  (3069, 832),
  (1135, 808),
  (1713, 809),
  (1001, 799),
  (2208, 791),
  (3258, 800),
  (272, 792),
  (1861, 792),
  (1964, 786),
  (1457, 812),
  (847, 773),
  (1599, 767),
  (40, 747),
  (2361, 759),
  (1223, 737),
  (518, 741),
  (2997, 747),
  (2798, 738),
  (3433, 727),
  (2544, 728),
  (2261, 731),
  (713, 726),
  (1707, 720),
  (1406, 726),
  (3344, 698),
  (1030, 699),
  (875, 692),
  (1576, 674),
  (1257, 668),
  (2888, 674),
  (1851, 658),
  (2209, 640),
  (1100, 636),
  (3272, 639),
  (278, 643),
  (1501, 628),
  (75, 618),
  (1926, 651),
  (1423, 595),
  (836, 586),
  (3091, 591),
  (2657, 576),
  (3354, 565),
  (2976, 568),
  (121, 570),
  (332, 568),
  (2284, 563),
  (460, 535),
  (1661, 577),
  (2570, 537),
  (1938, 541),
  (2097, 565),
  (1056, 530),
  (2833, 506),
  (3067, 513),
  (2465, 511),
  (1288, 491),
  (2345, 498),
  (3371, 489),
  (1506, 479),
  (365, 491),
  (1137, 476),
  (617, 480),
  (462, 466),
  (1671, 448),
  (165, 449),
  (3303, 447),
  (397, 419),
  (3092, 409),
  (2570, 406),
  (1374, 409),
  (1001, 399),
  (2281, 382),
  (666, 425),
  (800, 369),
  (36, 366),
  (2967, 367),
  (2497, 355),
  (1107, 333),
  (2737, 296),
  (3225, 280),
  (2608, 283),
  (3091, 271),
  (480, 262),
  (1814, 255),
  (1602, 243),
  (1193, 232),
  (64, 230),
  (3286, 229),
  (319, 222),
  (805, 198),
  (1427, 195),
  (2335, 179),
  (1670, 186),
  (33, 161),
  (723, 210),
  (164, 190),
  (3021, 192),
  (1534, 158),
  (973, 150),
  (1749, 151),
  (3204, 134),
  (2875, 136),
  (1117, 101),
  (329, 118),
  (2037, 116),
  (1329, 95),
  (417, 106),
  (1700, 98),
  (912, 82),
  (1185, 85),
  (2419, 74),
  (1891, 85),
  (109, 54),
  (3067, 33),
  (1587, 61),
  (568, 55),
  (1470, 44)],
 [(3620, 3806),
  (1458, 3805),
  (1201, 3801),
  (2680, 3785),
  (2581, 3786),
  (3438, 3771),
  (3221, 3772),
  (1868, 3767),
  (3733, 3758),
  (510, 3749),
  (869, 3752),
  (2427, 3737),
  (1291, 3737),
  (3289, 3741),
  (1614, 3719),
  (767, 3726),
  (2622, 3706),
  (2910, 3706),
  (2298, 3736),
  (1706, 3692),
  (2713, 3658),
  (1523, 3660),
  (3529, 3698),
  (353, 3672),
  (1811, 3666),
  (958, 3660),
  (1064, 3662),
  (3011, 3678),
  (3166, 3661),
  (2037, 3640),
  (2556, 3623),
  (1469, 3634),
  (408, 3598),
  (2184, 3597),
  (1702, 3601),
  (3638, 3601),
  (991, 3592),
  (214, 3584),
  (3112, 3591),
  (2324, 3583),
  (3790, 3582),
  (2927, 3576),
  (3300, 3577),
  (933, 3549),
  (2752, 3542),
  (1916, 3572),
  (533, 3556),
  (2422, 3542),
  (1583, 3570),
  (75, 3532),
  (741, 3523),
  (3645, 3512),
  (1775, 3509),
  (2647, 3494),
  (3428, 3497),
  (1673, 3481),
  (1022, 3483),
  (3351, 3475),
  (837, 3472),
  (2269, 3463),
  (3199, 3457),
  (2077, 3441),
  (3035, 3445),
  (2885, 3437),
  (689, 3430),
  (3598, 3419),
  (452, 3408),
  (1857, 3438),
  (1201, 3402),
  (2417, 3389),
  (859, 3378),
  (1389, 3389),
  (68, 3394),
  (740, 3375),
  (2810, 3356),
  (2690, 3344),
  (1134, 3320),
  (2323, 3324),
  (3180, 3315),
  (1630, 3320),
  (499, 3307),
  (2216, 3321),
  (1742, 3316),
  (2483, 3318),
  (1936, 3331),
  (3679, 3319),
  (1283, 3275),
  (742, 3260),
  (2121, 3263),
  (626, 3254),
  (1405, 3248),
  (3307, 3241),
  (200, 3285),
  (2909, 3237),
  (1831, 3213),
  (3514, 3264),
  (3196, 3203),
  (1730, 3199),
  (2742, 3210),
  (3705, 3178),
  (2401, 3175),
  (448, 3216),
  (2039, 3171),
  (3353, 3161),
  (122, 3159),
  (853, 3171),
  (3061, 3147),
  (2325, 3124),
  (1115, 3119),
  (1009, 3117),
  (61, 3104),
  (325, 3140),
  (1932, 3094),
  (2187, 3079),
  (2978, 3076),
  (2801, 3076),
  (1258, 3076),
  (593, 3062),
  (2002, 3056),
  (1584, 3067),
  (909, 3054),
  (3378, 3046),
  (194, 3039),
  (1000, 3029),
  (1382, 3015),
  (3149, 3014),
  (497, 3022),
  (3252, 3009),
  (1664, 3009),
  (3674, 2988),
  (2792, 2996),
  (60, 2986),
  (743, 2991),
  (596, 2974),
  (2956, 2973),
  (310, 2970),
  (3568, 2962),
  (3484, 2959),
  (1460, 2953),
  (416, 2941),
  (2285, 2939),
  (2111, 2924),
  (3794, 2920),
  (158, 2916),
  (2568, 2928),
  (2443, 2897),
  (1880, 2959),
  (734, 2901),
  (3143, 2902),
  (3554, 2878),
  (1175, 2878),
  (2938, 2875),
  (107, 2842),
  (628, 2864),
  (1530, 2843),
  (379, 2841),
  (975, 2844),
  (3242, 2857),
  (217, 2819),
  (3404, 2823),
  (1905, 2825),
  (3079, 2821),
  (2256, 2812),
  (846, 2826),
  (2567, 2802),
  (1599, 2844),
  (1291, 2782),
  (2878, 2786),
  (1371, 2821),
  (2047, 2769),
  (2351, 2768),
  (638, 2746),
  (2470, 2750),
  (3613, 2736),
  (2200, 2739),
  (415, 2746),
  (559, 2711),
  (1847, 2719),
  (3765, 2714),
  (3409, 2692),
  (1990, 2709),
  (1349, 2695),
  (1248, 2676),
  (265, 2685),
  (362, 2676),
  (3104, 2677),
  (118, 2652),
  (2592, 2654),
  (2348, 2643),
  (785, 2647),
  (2199, 2627),
  (2713, 2666),
  (3554, 2615),
  (3759, 2604),
  (564, 2611),
  (3379, 2597),
  (1281, 2588),
  (1858, 2603),
  (1163, 2596),
  (2010, 2585),
  (1034, 2580),
  (1452, 2568),
  (873, 2581),
  (3217, 2549),
  (3054, 2580),
  (1752, 2549),
  (1543, 2539),
  (3457, 2535),
  (134, 2512),
  (438, 2498),
  (3806, 2471),
  (2430, 2512),
  (1087, 2481),
  (1237, 2481),
  (2147, 2505),
  (2957, 2489),
  (193, 2466),
  (2823, 2453),
  (636, 2453),
  (3134, 2442),
  (1607, 2442),
  (1733, 2430),
  (1004, 2438),
  (3471, 2424),
  (858, 2415),
  (1963, 2446),
  (125, 2402),
  (3582, 2402),
  (3037, 2382),
  (2601, 2352),
  (2292, 2345),
  (1546, 2356),
  (536, 2344),
  (1293, 2337),
  (3403, 2335),
  (416, 2338),
  (2460, 2331),
  (1800, 2336),
  (1134, 2330),
  (3521, 2327),
  (2083, 2322),
  (2225, 2323),
  (1701, 2314),
  (2925, 2299),
  (1983, 2312),
  (715, 2300),
  (3206, 2285),
  (3048, 2274),
  (340, 2278),
  (3141, 2277),
  (3309, 2256),
  (1009, 2298),
  (3600, 2246),
  (2186, 2228),
  (838, 2239),
  (2075, 2213),
  (1157, 2224),
  (2811, 2212),
  (1315, 2216),
  (1873, 2213),
  (149, 2196),
  (1066, 2166),
  (699, 2208),
  (3389, 2172),
  (2345, 2164),
  (2261, 2157),
  (3689, 2151),
  (3190, 2142),
  (2130, 2124),
  (1988, 2118),
  (1011, 2121),
  (3576, 2107),
  (354, 2090),
  (1303, 2081),
  (2822, 2082),
  (3467, 2065),
  (2442, 2072),
  (3778, 2082),
  (233, 2064),
  (2558, 2054),
  (2235, 2047),
  (1737, 2094),
  (1615, 2024),
  (3255, 2027),
  (574, 2034),
  (42, 2015),
  (3016, 2008),
  (727, 2005),
  (1427, 2001),
  (3533, 1988),
  (2342, 1993),
  (2851, 1974),
  (2129, 1972),
  (465, 1983),
  (3801, 1945),
  (621, 1958),
  (1386, 1921),
  (3333, 1934),
  (1991, 1925),
  (1904, 1967),
  (2768, 1918),
  (799, 1921),
  (125, 1958),
  (1641, 1898),
  (349, 1890),
  (551, 1863),
  (2116, 1869),
  (1239, 1867),
  (2606, 1858),
  (969, 1881),
  (3123, 1825),
  (673, 1857),
  (2951, 1870),
  (195, 1830),
  (55, 1836),
  (1062, 1835),
  (3636, 1822),
  (3378, 1808),
  (2757, 1811),
  (1359, 1803),
  (2363, 1814),
  (3709, 1810),
  (1909, 1804),
  (1139, 1808),
  (387, 1792),
  (2174, 1797),
  (3483, 1768),
  (1754, 1760),
  (2392, 1768),
  (3236, 1770),
  (3781, 1744),
  (2957, 1731),
  (64, 1715),
  (749, 1715),
  (654, 1729),
  (1161, 1703),
  (1543, 1705),
  (2554, 1743),
  (485, 1684),
  (3324, 1686),
  (2444, 1686),
  (1452, 1683),
  (1598, 1637),
  (2618, 1652),
  (1040, 1679),
  (245, 1629),
  (3663, 1633),
  (1872, 1631),
  (3458, 1630),
  (3184, 1668),
  (3077, 1619),
  (721, 1611),
  (921, 1596),
  (2048, 1592),
  (403, 1609),
  (274, 1563),
  (788, 1570),
  (2824, 1556),
  (2545, 1540),
  (1931, 1524),
  (1093, 1538),
  (2023, 1522),
  (581, 1509),
  (889, 1497),
  (1179, 1487),
  (374, 1503),
  (3538, 1521),
  (2700, 1484),
  (153, 1480),
  (1347, 1462),
  (3299, 1459),
  (3428, 1458),
  (690, 1456),
  (524, 1464),
  (2386, 1492),
  (1794, 1439),
  (1247, 1442),
  (2967, 1414),
  (414, 1425),
  (981, 1433),
  (2844, 1397),
  (2640, 1385),
  (2194, 1382),
  (1464, 1377),
  (200, 1366),
  (2322, 1378),
  (3716, 1366),
  (526, 1349),
  (1060, 1378),
  (3374, 1364),
  (113, 1352),
  (2087, 1355),
  (1373, 1347),
  (748, 1358),
  (3484, 1336),
  (1987, 1322),
  (3766, 1315),
  (771, 1296),
  (1872, 1299),
  (840, 1287),
  (2754, 1287),
  (3135, 1284),
  (3695, 1282),
  (3017, 1330),
  (2225, 1280),
  (409, 1278),
  (935, 1279),
  (310, 1259),
  (2639, 1265),
  (599, 1263),
  (173, 1240),
  (1465, 1239),
  (3595, 1238),
  (1747, 1235),
  (3045, 1224),
  (1156, 1232),
  (1650, 1217),
  (3513, 1204),
  (2173, 1193),
  (3274, 1211),
  (1548, 1149),
  (2117, 1152),
  (1944, 1173),
  (982, 1137),
  (2234, 1126),
  (2799, 1155),
  (1337, 1122),
  (3357, 1083),
  (1057, 1069),
  (3113, 1076),
  (3546, 1065),
  (448, 1072),
  (1680, 1061),
  (2587, 1093),
  (897, 1032),
  (2138, 1033),
  (124, 1040),
  (994, 1028),
  (2470, 1003),
  (3374, 991),
  (1308, 990),
  (1825, 981),
  (2796, 976),
  (3053, 972),
  (784, 972),
  (405, 969),
  (204, 948),
  (3652, 949),
  (523, 949),
  (2269, 937),
  (899, 937),
  (3162, 949),
  (668, 918),
  (1985, 933),
  (3795, 909),
  (2469, 903),
  (2872, 891),
  (794, 876),
  (1105, 878),
  (1223, 872),
  (2173, 899),
  (442, 856),
  (3087, 840),
  (1322, 837),
  (2400, 837),
  (2506, 842),
  (3747, 831),
  (1766, 828),
  (3206, 813),
  (1515, 841),
  (3560, 799),
  (157, 812),
  (961, 804),
  (3656, 796),
  (2302, 797),
  (462, 760),
  (1186, 742),
  (761, 755),
  (924, 744),
  (2923, 727),
  (2171, 732),
  (3207, 720),
  (2516, 748),
  (1410, 710),
  (1254, 719),
  (3327, 711),
  (250, 734),
  (1091, 705),
  (2809, 683),
  (387, 670),
  (1737, 687),
  (3487, 708),
  (2410, 675),
  (3788, 657),
  (670, 653),
  (1932, 652),
  (1507, 705),
  (1292, 654),
  (3597, 628),
  (3206, 630),
  (782, 618),
  (2568, 618),
  (2678, 618),
  (3757, 602),
  (2192, 595),
  (420, 602),
  (510, 602),
  (183, 595),
  (3081, 615),
  (1074, 573),
  (2450, 568),
  (3468, 583),
  (2762, 537),
  (1384, 548),
  (2023, 540),
  (2338, 515),
  (1859, 506),
  (1657, 510),
  (3801, 491),
  (922, 488),
  (2934, 495),
  (260, 491),
  (1325, 491),
  (574, 483),
  (3104, 481),
  (3313, 466),
  (131, 474),
  (725, 451),
  (1510, 457),
  (3761, 435),
  (2238, 432),
  (1966, 420),
  (3517, 418),
  (981, 408),
  (1858, 404),
  (1144, 400),
  (2678, 396),
  (847, 375),
  (2069, 369),
  (2794, 368),
  (2926, 374),
  (1072, 356),
  (3798, 364),
  (3254, 337),
  (630, 332),
  (1243, 330),
  (892, 326),
  (1383, 327),
  (1480, 320),
  (2007, 314),
  (265, 316),
  (2318, 304),
  (2168, 300),
  (442, 302),
  (164, 290),
  (3690, 287),
  (2603, 289),
  (3517, 271),
  (790, 267),
  (557, 240),
  (1735, 239),
  (1494, 230),
  (674, 223),
  (2494, 262),
  (3120, 227),
  (2706, 218),
  (495, 201),
  (1206, 209),
  (767, 169),
  (3758, 188),
  (3538, 168),
  (2587, 177),
  (1613, 163),
  (2204, 156),
  (275, 158),
  (999, 148),
  (3302, 112),
  (690, 108),
  (1149, 104),
  (2489, 106),
  (3007, 118),
  (3480, 88),
  (2339, 71),
  (3163, 83),
  (1719, 59),
  (2889, 49),
  (2431, 34),
  (1835, 99),
  (3764, 62),
  (2185, 47),
  (2026, 35),
  (3685, 47),
  (1429, 46),
  (1287, 51),
  (2686, 77),
  (3387, 43)],
 [(2837, 3802),
  (1634, 3799),
  (2964, 3793),
  (1418, 3786),
  (2358, 3790),
  (867, 3781),
  (3611, 3775),
  (2034, 3772),
  (671, 3789),
  (2581, 3758),
  (3261, 3753),
  (3718, 3754),
  (1783, 3732),
  (3412, 3724),
  (2196, 3732),
  (1668, 3717),
  (1244, 3718),
  (590, 3714),
  (787, 3683),
  (1465, 3671),
  (448, 3677),
  (310, 3710),
  (913, 3657),
  (3263, 3659),
  (2294, 3640),
  (3096, 3654),
  (2385, 3627),
  (61, 3615),
  (606, 3605),
  (2045, 3594),
  (1441, 3586),
  (1124, 3593),
  (1821, 3570),
  (1312, 3575),
  (1013, 3567),
  (3787, 3551),
  (3681, 3553),
  (2234, 3546),
  (364, 3546),
  (749, 3541),
  (3513, 3541),
  (3125, 3550),
  (1547, 3530),
  (1251, 3529),
  (2361, 3527),
  (1707, 3512),
  (2744, 3555),
  (466, 3544),
  (107, 3504),
  (2598, 3491),
  (1876, 3515),
  (3657, 3478),
  (1358, 3494),
  (1146, 3480),
  (2855, 3473),
  (2061, 3458),
  (332, 3462),
  (3048, 3467),
  (169, 3466),
  (3235, 3464),
  (1428, 3460),
  (880, 3451),
  (3540, 3438),
  (1290, 3431),
  (749, 3433),
  (257, 3419),
  (1055, 3416),
  (1997, 3411),
  (817, 3403),
  (3628, 3397),
  (2532, 3393),
  (3351, 3396),
  (1384, 3397),
  (2831, 3378),
  (3762, 3379),
  (2377, 3356),
  (1166, 3347),
  (3520, 3346),
  (2098, 3346),
  (971, 3330),
  (1274, 3326),
  (3455, 3314),
  (2627, 3324),
  (2487, 3313),
  (211, 3317),
  (3080, 3298),
  (529, 3284),
  (3008, 3280),
  (3704, 3267),
  (1666, 3266),
  (3565, 3260),
  (2880, 3269),
  (1370, 3246),
  (368, 3267),
  (2204, 3240),
  (1925, 3247),
  (1212, 3242),
  (857, 3241),
  (645, 3222),
  (2045, 3209),
  (2791, 3199),
  (2587, 3193),
  (1012, 3189),
  (1952, 3185),
  (2478, 3182),
  (1527, 3169),
  (2701, 3162),
  (2894, 3171),
  (3376, 3148),
  (3074, 3158),
  (1258, 3152),
  (1105, 3152),
  (2369, 3144),
  (1408, 3152),
  (741, 3144),
  (329, 3142),
  (3743, 3121),
  (520, 3110),
  (138, 3101),
  (1494, 3100),
  (997, 3088),
  (2832, 3087),
  (2283, 3074),
  (1802, 3076),
  (3023, 3054),
  (1083, 3060),
  (44, 3044),
  (2653, 3033),
  (1201, 3040),
  (2109, 3035),
  (290, 3029),
  (2472, 3021),

In [59]:
tp_list

[array([[ 909.05844855,   79.95339314],
        [1183.59453614,   81.23953709],
        [ 320.07861837,  115.9331578 ],
        ...,
        [1053.03199557, 3779.32261461],
        [2698.44143059, 3762.1120944 ],
        [3345.52081554, 3782.9826098 ]]),
 array([[2217.93849436,   48.56030575],
        [1428.18365589,   48.71411461],
        [3576.73989299,   53.90427004],
        ...,
        [ 765.5521276 , 3723.45041427],
        [2426.39195645, 3732.99240825],
        [1288.55971098, 3733.66112984]]),
 array([[3143.59125048,  108.3437677 ],
        [1994.27966934,  105.87379276],
        [1108.08609594,   66.14742502],
        ...,
        [3259.97940591, 3752.02335018],
        [1413.75391603, 3785.1432941 ],
        [2961.198131  , 3789.07724623]]),
 array([[1132.17692055,   47.50930411],
        [  78.90150901,   45.91909591],
        [3711.34850424,  107.96616541],
        ...,
        [2028.43140692, 3765.42262811],
        [3723.33237305, 3741.95953083],
        [2806.62864339, 3788.96926858]]),
 array([[ 806.46895797,   90.00003531],
        [3175.12208222,   62.94696956],
        [3554.12463838,   42.82738669],
        ...,
        [3064.68544024, 3742.29340876],
        [3712.08051281, 3755.5655315 ],
        [2819.27966629, 3737.18299243]]),
 array([[1385.98433985,   39.28992905],
        [3284.18626518,  108.40857447],
        [3439.51324908,   54.93001767],
        ...,
        [1500.68400481, 3779.25244082],
        [2454.99105726, 3766.73808289],
        [2715.95992861, 3749.70234326]]),
 array([[1009.89333579,   61.48098442],
        [ 599.11447044,  122.12082257],
        [3112.16288738,   48.21655329],
        ...,
        [1909.38109746, 3735.81599652],
        [2702.46214165, 3776.58867072],
        [2823.72837356, 3779.39213735]]),
 array([[1242.38921999,  218.63075827],
        [ 672.58087314,  227.81953819],
        [1329.47958938,  251.78524266],
        ...,
        [1664.40155021, 3749.90891698],
        [2516.40684961, 3748.86054594],
        [2608.21430019, 3789.49145367]]),
 array([[ 315.45030532,   63.12235583],
        [ 501.38145621,  113.81943763],
        [1314.71222377,   75.11872938],
        ...,
        [ 351.43801786, 3774.14087672],
        [2618.17327965, 3751.83440703],
        [3015.86181256, 3769.88625488]]),
 array([[1098.90399118,   45.63608941],
        [2992.45388455,   94.22439876],
        [1589.526386  ,   72.08639411],
        ...,
        [2139.88572945, 3790.53597488],
        [ 232.81158931, 3763.31030114],
        [ 619.23339312, 3773.29058238]]),
 array([[2320.54571664,   47.70593081],
        [1837.60701074,  107.96051512],
        [3670.78588152,   58.81763929],
        ...,
        [1585.37270232, 3743.76538302],
        [1946.68503214, 3790.50165996],
        [3509.8437652 , 3736.76074035]]),
 array([[2801.45483142,  112.71995483],
        [3298.58603993,   63.3068385 ],
        [ 388.87290724,   95.21432162],
        ...,
        [ 264.03831723, 3755.91997875],
        [2365.81488812, 3763.82690559],
        [1171.30940758, 3728.78298903]]),
 array([[3106.04611387,   60.85877371],
        [2093.27210004,   68.55533341],
        [1116.65192904,   97.72131336],
        ...,
        [1469.80781642, 3767.28233935],
        [2751.94606428, 3768.72379255],
        [1207.01907998, 3791.22434222]]),
 array([[1831.1680168 ,   66.77327733],
        [ 902.18552982,  100.36556671],
        [2001.52600475,   49.41632514],
        ...,
        [2031.13076951, 3738.20597741],
        [ 547.06349703, 3771.43186321],
        [ 940.11282625, 3783.94805865]]),
 array([[2899.78127228,   65.73254497],
        [3187.35948925,   45.56702543],
        [3761.39864734,  124.75308213],
        ...,
        [2479.66560761, 3767.2363042 ],
        [3353.35263913, 3772.19225251],
        [3630.1576725 , 3786.88051599]]),
 array([[1066.29822567,   97.8719913 ],
        [2478.81776129,   77.91910012],
        [3423.5036593 ,  111.63193704],
        ...,
        [1071.88523991, 3767.99561147],
        [3383.96032944, 3739.82915786],
        [ 545.71590938, 3762.12165254]]),
 array([[1048.06016538,   42.62144638],
        [1752.94040816,   59.26312925],
        [3576.56865774,   68.22180076],
        ...,
        [1593.9805508 , 3748.09514548],
        [2050.65087549, 3783.75912011],
        [3005.71709466, 3778.86617641]]),
 array([[2089.35687713,   62.28207985],
        [2950.13745119,   58.92750808],
        [2636.93749887,   54.57202159],
        ...,
        [ 358.52827903, 3728.09090408],
        [1669.56567475, 3770.11557062],
        [2312.58629323, 3745.76923403]]),
 array([[ 324.89238194,   44.19092741],
        [1025.90339879,   95.01639597],
        [1294.92989986,   50.22808093],
        ...,
        [1347.02964276, 3789.64931854],
        [2982.95782529, 3780.69918156],
        [3734.01674674, 3766.42930679]]),
 array([[  72.9906944 ,   54.44119487],
        [3390.67799866,   58.62402766],
        [2407.58166285,  113.70774471],
        ...,
        [2646.99110219, 3762.17962213],
        [2878.56660374, 3775.56718723],
        [3098.4734338 , 3751.15752593]]),
 array([[ 221.88877377,   81.74794642],
        [1777.69394023,   49.41266177],
        [2401.94671429,  102.87180042],
        ...,
        [ 477.39874451, 3764.11125222],
        [2778.75576776, 3783.30875095],
        [3164.93826676, 3739.72303465]]),
 array([[2665.53229099,   96.49509542],
        [1706.31202317,  118.80693699],
        [1447.15116711,   85.09329439],
        ...,
        [3581.90003057, 3748.92150718],
        [1142.93684809, 3765.76377774],
        [2892.18895003, 3791.40400616]]),
 array([[ 756.75880546,   53.84503822],
        [ 184.58600287,   46.42608402],
        [2599.03504395,   60.50864297],
        ...,
        [2948.23396357, 3733.46163759],
        [ 161.54485555, 3766.32266026],
        [1464.90065293, 3772.13544288]]),
 array([[2052.27100744,   47.59980149],
        [2219.80064986,  101.67377031],
        [ 398.23218965,   57.63371251],
        ...,
        [ 208.26311431, 3783.13389739],
        [1543.07168574, 3763.43578227],
        [3767.62610404, 3767.50829578]]),
 array([[ 983.31197656,   62.91705845],
        [1892.16962727,   56.71198275],
        [2189.72871028,   94.29511992],
        ...,
        [2423.95146174, 3738.33025598],
        [ 966.49725195, 3727.55539485],
        [1277.83259943, 3773.16969035]]),
 array([[ 794.81677636,   62.32823146],
        [2572.83681044,   62.77375315],
        [3037.85436017,   59.05565713],
        [2747.81312495,  126.52788682],
        [1220.53662476,   93.41786642],
        [1172.54198242,  101.20510347],
        [3550.46978731,   99.03131602],
        [2348.14941215,   94.53225016],
        [ 463.08796684,  127.02090985],
        [1371.24264276,  127.14558566],
        [2033.80961894,  164.33211806],
        [1536.76415074,  175.71134021],
        [1792.24618392,  124.40957967],
        [2193.12798867,  144.57767211],
        [ 610.08515081,  132.68523053],
        [1941.63157112,  203.85667254],
        [1009.24861817,  138.65639365],
        [2596.70149076,  185.30041741],
        [3122.0469462 ,  218.30128279],
        [3297.59691791,  197.23699449],
        [ 304.49302905,  232.42106083],
        [2858.08194667,  166.72783853],
        [3476.32461711,  236.19219275],
        [3672.98883589,  217.08159951],
        [1102.83824899,  196.90406706],
        [2964.77287263,  263.53786756],
        [ 854.69138642,  225.54774746],
        [ 920.8537415 ,  241.38253968],
        [2719.05962356,  243.95560413],
        [ 187.76813506,  232.48236482],
        [1593.68571969,  255.80726944],
        [2125.01495768,  269.37216403],
        [ 474.47801336,  273.98418316],
        [3564.97532712,  259.58604812],
        [1301.16172966,  288.89342867],
        [3377.25678577,  269.40814292],
        [1688.68962857,  322.17613649],
        [1969.60951204,  261.91802539],
        [ 355.43335835,  330.82497077],
        [2190.052479  ,  286.79560521],
        [2596.05240899,  280.26063521],
        [3133.68906613,  297.78148704],
        [2434.05006864,  318.22611645],
        [2817.57900633,  333.58057469],
        [  95.00234387,  381.63339262],
        [3209.49529607,  354.77008216],
        [ 600.14547298,  355.41249196],
        [1178.94746695,  392.62259662],
        [3511.56771871,  385.06044124],
        [3779.70939732,  352.77650883],
        [2912.71655565,  348.51785571],
        [1779.18303571,  415.12110562],
        [1086.22270488,  400.82899585],
        [ 929.08662115,  384.17213508],
        [3394.11832381,  418.5633364 ],
        [2107.21131461,  390.50565314],
        [2622.9402205 ,  425.69389234],
        [1302.36743946,  445.51241628],
        [1612.48008616,  411.38852436],
        [ 672.04342892,  464.65560497],
        [ 815.08385651,  450.8608874 ],
        [2444.91032213,  499.1761499 ],
        [ 297.21444332,  482.70157251],
        [ 481.26763573,  496.29867064],
        [1912.94270961,  510.00668798],
        [3432.52409418,  511.96047334],
        [2100.63983229,  522.12972746],
        [2297.63328437,  529.01169767],
        [2703.11974681,  535.1460278 ],
        [ 741.55959868,  531.42403149],
        [1982.94980374,  540.87724035],
        [1104.32444074,  568.06751555],
        [1307.83596767,  551.08237756],
        [1756.89425534,  577.31812289],
        [3006.46193374,  570.23439261],
        [ 885.98262647,  605.0149646 ],
        [2734.172975  ,  581.23518136],
        [3110.86898848,  610.60981177],
        [ 434.20389552,  621.71512805],
        [1116.55436081,  659.89227938],
        [1238.93796737,  698.91069001],
        [2349.86150462,  669.04425869],
        [ 523.76883492,  659.1556101 ],
        [2874.36481569,  699.24632178],
        [1998.37433601,  677.31309759],
        [ 930.99402648,  750.28458172],
        [ 819.25080127,  746.69578093],
        [3561.15629485,  744.8684402 ],
        [2152.05608479,  731.00793548],
        [ 288.88458601,  752.69789237],
        [ 684.59631983,  736.55121943],
        [2433.19980851,  776.85712181],
        [2302.95797555,  837.60871618],
        [2592.44664859,  779.51135219],
        [1175.33312288,  770.69686686],
        [1026.0530257 ,  794.26818683],
        [ 537.23903225,  853.22741328],
        [ 126.01081031,  869.73362284],
        [1422.42020341,  829.0622561 ],
        [2805.6052989 ,  861.50425207],
        [ 774.91012336,  849.82807911],
        [ 945.07663337,  840.03868373],
        [1764.6002023 ,  886.86719463],
        [3540.51405047,  877.10621085],
        [ 570.66337236,  928.60732984],
        [2057.19148936,  899.07684606],
        [ 221.44132077,  945.53936609],
        [3368.35245637,  910.02157165],
        [1461.99818016,  925.61643778],
        [3051.5936255 ,  952.47749742],
        [1569.80560577,  941.80965813],
        [ 454.35271927,  962.61957156],
        [2601.90343176,  990.70478851],
        [2785.01556867,  969.28203868],
        [1200.67703329, 1039.35153814],
        [1110.60837844, 1019.24494934],
        [2511.39734171,  993.73044479],
        [3418.17931098, 1020.74778464],
        [3145.52427966, 1063.31941836],
        [ 718.09055251, 1027.99636335],
        [2920.39112168, 1007.43828775],
        [1685.7291022 ,  998.16349203],
        [ 257.79223881, 1050.55745274],
        [ 207.77476609, 1066.76007939],
        [2410.68354552, 1047.22728801],
        [ 606.17093362, 1066.17936532],
        [2252.74517492, 1074.96844024],
        [3687.71392723, 1104.05938938],
        [3002.19946072, 1128.66870719],
        [1845.34723205, 1121.66879008],
        [2762.70463743, 1184.44191141],
        [3381.39195817, 1181.44699529],
        [ 220.75065489, 1150.16765305],
        [ 503.09153114, 1184.99170455],
        [2150.67290684, 1134.31198408],
        [ 312.5181027 , 1173.61488251],
        [2574.86105129, 1211.3276701 ],
        [1665.48319279, 1218.10326903],
        [2713.41262546, 1210.5009743 ],
        [2212.34533675, 1232.73527196],
        [1076.89380531, 1232.13598528],
        [ 915.29696547, 1234.10972327],
        [3150.19323476, 1258.54000405],
        [1758.88755832, 1254.5966563 ],
        [1455.54368433, 1325.87526988],
        [2018.43624626, 1307.03800075],
        [2474.50760224, 1300.85925685],
        [3050.66443713, 1352.53369563],
        [1082.04445684, 1356.1791021 ],
        [ 181.95059111, 1337.16102731],
        [2793.00374289, 1308.34269056],
        [2682.7054955 , 1375.60619844],
        [ 363.72118359, 1343.47481664],
        [3269.39232612, 1353.55424573],
        [2073.91683001, 1403.0014989 ],
        [3388.34770972, 1379.82567497],
        [ 854.34074759, 1412.88954295],
        [1156.10174333, 1424.26723493],
        [1787.44880104, 1447.70848574],
        [ 713.30118343, 1409.61065089],
        [3660.28519606, 1473.12053557],
        [2851.61694266, 1485.91723489],
        [3082.58370483, 1465.74576496],
        [2352.13869406, 1472.30378962],
        [3536.65495589, 1450.92414962],
        [1956.76657644, 1514.28978622],
        [1694.02657834, 1506.81890015],
        [ 123.89870588, 1479.50282738],
        [ 410.53980409, 1484.36408245],
        [1142.85064414, 1528.37071425],
        [ 520.79964556, 1529.4527042 ],
        [2495.20074068, 1497.61635553],
        [ 263.77917996, 1509.64026941],
        [2707.63789713, 1502.57924295],
        [2611.96759178, 1536.60670999],
        [1391.93650048, 1588.85170138],
        [ 728.06893691, 1621.6970426 ],
        [3385.88691053, 1551.790827  ],
        [2122.13864284, 1588.20844374],
        [1093.83285644, 1566.32990627],
        [1946.78941538, 1574.40668132],
        [ 145.03470608, 1606.85770887],
        [ 813.78169524, 1584.79344764],
        [3022.25086864, 1624.18906639],
        [1350.29462585, 1621.47835718],
        [2743.66065723, 1668.52593791],
        [3656.03509968, 1618.59686488],
        [3122.99794341, 1653.00006494],
        [1694.04387657, 1625.93627451],
        [ 937.69122297, 1655.41639106],
        [ 432.12796533, 1660.62735734],
        [1448.42292945, 1681.49376917],
        [3458.17035853, 1671.41493492],
        [2038.45931674, 1725.12943205],
        [3555.20968211, 1691.24102485],
        [2952.63692308, 1722.94395604],
        [  77.8475861 , 1759.03051488],
        [1525.34599552, 1735.89606684],
        [2789.29243256, 1758.779104  ],
        [ 190.19142886, 1772.93807501],
        [2149.77884245, 1788.17158286],
        [3407.21002022, 1812.43236846],
        [3188.28490724, 1800.01038247],
        [3707.7084422 , 1843.98544013],
        [1334.47259699, 1819.22708018],
        [2532.17619636, 1860.95780372],
        [ 364.81348315, 1833.34382022],
        [ 552.50537236, 1851.87180437],
        [2485.20628547, 1882.81904174],
        [ 648.44057947, 1875.08478778],
        [2104.14258759, 1916.83757458],
        [1654.7527608 , 1949.46783691],
        [ 170.45306221, 1914.30714801],
        [1336.88018398, 1961.61556152],
        [ 327.67074669, 1948.70764891],
        [3462.10573841, 1975.43907174],
        [1387.16242677, 1982.21863661],
        [3227.71446311, 1956.71436904],
        [ 877.97703909, 1959.2197794 ],
        [2082.60358829, 2059.25537299],
        [ 601.02527156, 1998.38941846],
        [3538.16357669, 2024.33654285],
        [1333.21451566, 2092.72483172],
        [1623.7260783 , 2038.63896104],
        [1952.18414663, 2133.06634292],
        [ 978.99153535, 2066.79759688],
        [ 754.84377252, 2136.81808269],
        [ 636.78365357, 2155.58859711],
        [2535.31955485, 2145.5618442 ],
        [2394.12677837, 2133.95194436],
        [ 499.28840503, 2161.2758231 ],
        [2066.68635017, 2128.63995333],
        [3302.23164863, 2128.35893885],
        [ 269.36842105, 2195.21230912],
        [3192.52794624, 2230.08135579],
        [ 927.17692849, 2223.77847796],
        [1106.31234772, 2270.78900692],
        [1940.35355582, 2205.78334577],
        [1813.07698436, 2198.33970107],
        [1361.60061941, 2238.49502425],
        [2696.3750333 , 2253.90926736],
        [1595.12206754, 2260.14900748],
        [ 164.36446537, 2258.26191277],
        [2435.2148316 , 2289.34005159],
        [3367.42338176, 2326.06612834],
        [3553.84150301, 2305.86031305],
        [3036.0054821 , 2370.69538538],
        [3700.13641566, 2346.41245136],
        [ 711.97257222, 2317.81816916],
        [1405.65928542, 2332.20069153],
        [2685.26478709, 2400.74960086],
        [3476.80533298, 2441.09935324],
        [2330.46740438, 2443.10632668],
        [3588.71940663, 2419.27531538],
        [1116.42922425, 2416.28893905],
        [2461.51642387, 2442.57952504],
        [ 170.23133276, 2402.24467756],
        [2547.07487217, 2450.75982469],
        [ 302.73159819, 2426.33002417],
        [1674.5726989 , 2438.51857552],
        [3267.67345094, 2424.96541336],
        [3373.97388305, 2468.90694809],
        [3693.38193765, 2531.80083702],
        [1961.49360906, 2494.33254301],
        [ 822.74541129, 2495.57135686],
        [2695.35448255, 2479.38147994],
        [1438.69476665, 2561.47428989],
        [2889.32984895, 2498.0943222 ],
        [ 915.24762804, 2498.85472543],
        [3506.67814048, 2518.39474978],
        [2370.708468  , 2535.89648783],
        [1239.57293408, 2532.19420016],
        [2157.34337306, 2537.76497038],
        [ 433.26392585, 2559.81536203],
        [ 322.33460353, 2556.37439442],
        [1508.34388168, 2611.53203199],
        [1792.83900856, 2579.65728707],
        [2974.42517662, 2625.05104084],
        [3286.73644633, 2623.02753184],
        [2899.15749875, 2631.6908372 ],
        [1098.64341114, 2669.9398254 ],
        [2484.52312134, 2604.79692527],
        [3776.8769855 , 2610.27209945],
        [1268.16339253, 2651.81126194],
        [2764.45713088, 2683.01967935],
        [ 489.91441137, 2656.13261164],
        [3510.07126383, 2647.74033218],
        [3418.07086498, 2689.00553786],
        [2921.65177064, 2738.79173306],
        [2204.38178251, 2705.74317877],
        [ 336.04711617, 2722.82743414],
        [1063.27900536, 2706.47347436],
        [ 654.01614508, 2733.93829481],
        [1929.93435815, 2797.2881393 ],
        [1195.36530318, 2731.7607205 ],
        [2623.23776267, 2773.14109648],
        [ 156.22487206, 2758.94880145],
        [2822.44448541, 2779.58447517],
        [1553.31359561, 2795.79677369],
        [1754.79118185, 2823.9560224 ],
        [ 769.8236412 , 2886.0486507 ],
        [2314.63625736, 2879.1333347 ],
        [ 223.11491571, 2949.62334437],
        [2684.68797262, 2875.41999227],
        [3132.34741164, 2922.04994493],
        [ 104.2063755 , 2928.64126702],
        [2598.48181637, 2950.14197599],
        [1421.71349862, 2944.47711968],
        [2396.22436883, 2998.85312843],
        [2513.60357107, 3029.05473663],
        [2965.57456751, 3024.04116126],
        [3366.48048268, 2983.61858729],
        [2740.44624063, 3019.83799788],
        [1906.08418871, 3031.33585208],
        [ 628.5949233 , 3078.50908235],
        [ 201.68407305, 3016.19785736],
        [ 498.21984983, 3064.7454539 ],
        [3077.93454598, 3039.0562876 ],
        [3219.15498321, 3045.82772962],
        [2465.34237288, 3078.92051844],
        [1567.16308162, 3067.45583524],
        [2970.07496035, 3120.71579708],
        [2011.40158864, 3140.1845213 ],
        [3377.99706759, 3121.40755659],
        [1104.45445156, 3162.01597466],
        [ 692.53655097, 3151.7320871 ],
        [2364.54980305, 3192.06631826],
        [ 127.27883316, 3201.93563382],
        [1320.50474076, 3220.14992817],
        [3183.08635552, 3254.64059952],
        [2000.65950404, 3304.34806512],
        [ 443.32550725, 3289.05117668],
        [3595.80767585, 3293.20145527],
        [ 883.39342061, 3320.55496811],
        [1626.43922422, 3349.79594188],
        [1755.39088579, 3421.0389448 ],
        [ 202.86900837, 3353.6816087 ],
        [1146.9290377 , 3385.24353747],
        [2009.48027472, 3413.51669062],
        [  81.17928258, 3492.93221083],

In [46]:
tp_config

(0.25, 0.4)

In [52]:
import trackpy as tp

In [50]:
TrackParticleSize = RADIUS*2-1
curr_adpmass = 0
sep = round(TrackParticleSize*tp_config[1])
scale = tp_config[0]  # Scale factor (0.5 means reducing the size to half)

In [53]:
tp_list = []
for img in label_images:
    output_image = img
    small_image = cv2.resize(output_image, None, fx=scale, fy=scale, interpolation=cv2.INTER_AREA)
    # Adjust parameters based on the scale
    small_sep = int(sep * scale)
    small_diameter = int(TrackParticleSize * scale)
    if small_diameter % 2 == 0:
        small_diameter += 1
    coorTrack = tp.locate(small_image, diameter=small_diameter, minmass=curr_adpmass, separation=small_sep)
    #coorTrack.loc[:,'prob']=[output_image[getattr(coor,'y'),getattr(coor,'x')] for coor in np.floor(coorTrack[['x','y']]).astype('int').itertuples()]
    coorTrack['x'] *= (1/scale)
    coorTrack['y'] *= (1/scale)
    coords = coorTrack[['x', 'y']].values
    tp_list.append(coords)
    print(len(coords))

576
626
615
541
540
647
607
627
573
598
636
631
564
674
584
516
604
601
624
603
540
635
595
589
642
379
358
411
441
413
412
697
599
614
594
632
610
610
473
584
546
623
556
625
505
394
394
387
398
422
412
561
573
576
597
545
580
490
471
419
391
440
471
444
463
506
491
454
476
473
507
465
497
470
480
438
635
638
546
494
568
469
604
449

In [54]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in tp_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [61]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in tp_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [62]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,1037.058449,207.953393,00000@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
1,1311.594536,209.239537,00001@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
2,448.078618,243.933158,00002@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
3,696.817166,182.958715,00003@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
4,1452.810437,222.935349,00004@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
...,...,...,...,...
44753,3042.522307,3880.208089,00444@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
44754,3779.807710,3832.280884,00445@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
44755,3303.087922,3876.442209,00446@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
44756,2833.609561,3863.584738,00447@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
44757,2659.237131,3918.437945,00448@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc

In [63]:
import starfile
starfile.write(df, f'{RESULT_DIR}/tp_particles.star')

### Nonmax

In [66]:
import pycuda.driver as drv
from center_finding import cleanCanList, pad_image, reLev, reNorm, scoreGpu, getMax, getMax3, gaussian_kernel_2d_opencv, reshape

In [64]:
nms_config

(0.5, 0.6)

In [65]:
#ratio=1
pnum=2000 #initial filtering, larger if candidate is more
pCan=nms_config[0] #the grid size smaller will generate more candidate
overlap=nms_config[1] #allow for overlap
psize=RADIUS*2

# Nor affect too much
level=3
nSep=10
nIter=100

In [67]:
nms_list = []
for idx, img in enumerate(label_images):
    # if idx == 6:
    #     break
    heatArr=pad_image(img)
    heatArr=reNorm(heatArr, nSep)
    heatArr=reLev(heatArr,level)
    gaus= gaussian_kernel_2d_opencv(kernel_size = psize,sigma = 0)

    # canList,score=scoreGpuLaunch(heatArr,gaus,psize, gsize, nIter, fscore)
    gsize=psize*pCan
    heat=heatArr.astype(np.float32)
    gaus=gaus.astype(np.float32)
    score=np.zeros(heat.shape).astype(np.float32)
    [sizex,sizey]=heat.shape
    sizex = int(sizex)
    sizey = int(sizey)
    psize = int(psize)
    gsize = int(gsize)

    func = scoreGpu

    tx=16
    ty=16
    bx=(sizex-1)//tx+1
    by=(sizey-1)//ty+1
    print('get score gpu',tx, ty, bx, by, gsize, psize)


    func(drv.In(heat), drv.In(gaus), drv.Out(score), np.int32(sizex), np.int32(sizey), np.int32(psize),
        block=(tx, ty, 1), grid=(int(bx), int(by)))

    # # Calculate necessary dimensions and convert all to int
    numx = int((sizex - 1) // gsize + 1)
    numy = int((sizey - 1) // gsize + 1)
    num = numx * numy
    tnum = num * 5

    # # Create the result array
    res = np.zeros(tnum).astype(np.float32)

    # # Block and grid dimensions
    bx = (numx - 1) // tx + 1
    by = (numy - 1) // ty + 1

    # Get the function from the module
    func = getMax

    # Call the function, ensure all parameters are the correct type
    func(drv.In(score), drv.Out(res), np.int32(gsize), np.int32(sizex), np.int32(sizey), np.int32(numx),
        block=(16, 16, 1), grid=(bx, by, 1))

    # Make sure all dimensions and sizes are properly cast to np.int32 to avoid ambiguity
    niter = np.int32(nIter)
    gsize = np.int32(gsize)
    sizex = np.int32(sizex)
    sizey = np.int32(sizey)
    numx = np.int32(numx)
    tnum = np.int32(num)

    print('get Max3', tx, ty, bx, by, niter, 'other : ', gsize, sizex, sizey, numx, tnum)
    func = getMax3
    # Ensuring the correct parameter order and type for the kernel invocation
    func(drv.In(score), drv.InOut(res), gsize, sizex, sizey, numx, tnum, niter,
            block=(16, 16, 1), grid=(bx, by, 1))

    canList=reshape(res,num)

    print('Number of Particles before:', len(canList))
    if(len(canList)>pnum):
        canList=canList[:pnum]


    canList=cleanCanList(canList,overlap,psize)
    #canList=reCan(canList,ratio)
    print('Number of Particles:', len(canList))
    nms_list.append([(r[1],r[0]) for r in canList])

get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3416
Number of Particles: 627
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3485
Number of Particles: 679
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3487
Number of Particles: 662
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3116
Number of Particles: 596
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3095
Number of Particles: 600
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 691
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3469
Number of Particles: 666
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3408
Number of Particles: 686
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3470
Number of Particles: 603
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3463
Number of Particles: 663
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3477
Number of Particles: 698
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3467
Number of Particles: 707
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3455
Number of Particles: 614
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3461
Number of Particles: 740
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 623
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3451
Number of Particles: 562
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3468
Number of Particles: 647
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3473
Number of Particles: 652
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3443
Number of Particles: 666
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 656
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3447
Number of Particles: 586
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3462
Number of Particles: 704
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3457
Number of Particles: 646
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3479
Number of Particles: 627
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3385
Number of Particles: 726
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3263
Number of Particles: 472
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3228
Number of Particles: 445
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3294
Number of Particles: 482
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3402
Number of Particles: 497
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3364
Number of Particles: 477
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3362
Number of Particles: 455
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3429
Number of Particles: 768
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3451
Number of Particles: 646
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3475
Number of Particles: 668
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3465
Number of Particles: 661
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3477
Number of Particles: 676
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3318
Number of Particles: 657
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3456
Number of Particles: 664
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3385
Number of Particles: 505
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3472
Number of Particles: 631
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3454
Number of Particles: 591
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3487
Number of Particles: 664
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3335
Number of Particles: 610
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3457
Number of Particles: 668
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3011
Number of Particles: 580
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3296
Number of Particles: 461
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3222
Number of Particles: 462
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3311
Number of Particles: 467
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3290
Number of Particles: 456
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3331
Number of Particles: 476
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3312
Number of Particles: 453
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3432
Number of Particles: 615
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3444
Number of Particles: 634
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3469
Number of Particles: 617
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3474
Number of Particles: 627
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3437
Number of Particles: 578
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3459
Number of Particles: 599
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3308
Number of Particles: 533
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3405
Number of Particles: 507
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3342
Number of Particles: 460
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3284
Number of Particles: 448
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3350
Number of Particles: 480
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3385
Number of Particles: 513
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3324
Number of Particles: 503
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3383
Number of Particles: 501
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3445
Number of Particles: 528
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3441
Number of Particles: 529
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3287
Number of Particles: 496
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3320
Number of Particles: 529
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3390
Number of Particles: 504
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3402
Number of Particles: 540
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3372
Number of Particles: 512
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3331
Number of Particles: 563
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3306
Number of Particles: 520
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3375
Number of Particles: 556
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3382
Number of Particles: 512
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3468
Number of Particles: 669
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3484
Number of Particles: 672
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3452
Number of Particles: 584
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3326
Number of Particles: 511
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3459
Number of Particles: 598
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3309
Number of Particles: 535
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3429
Number of Particles: 708
get score gpu 16 16 240 240 64 128
get Max3 16 16 4 4 100 other :  64 3840 3840 60 3600
convert
Number of Particles before: 3084
Number of Particles: 491

In [68]:
import matplotlib
for idx, (test_image, _, grid, _) in enumerate(full_dataset):
    # if idx == 6:
    #     break
    if idx % 30 == 0:
    # else:
        label_image = label_images[idx]
        _, ax = plt.subplots(figsize=(12, 12))
        ax.imshow(processed_micrographs[idx], cmap='gray')
        ax.imshow(label_image, cmap='inferno', alpha=0.4)

        for indx in nms_list[idx]:
            x, y = indx
            c = matplotlib.patches.Circle((x, y), radius=RADIUS, fill=False, color='r')
            ax.add_patch(c)
        plt.show()

Output hidden; open in https://colab.research.google.com to view.

In [69]:
import pandas as pd

for idx, fname in enumerate(fnames):
    # Create the adjusted list of tuples for current index
    adjusted_c_list = [(x + BORDER, y + BORDER) for x, y in nms_list[idx]]

    # Create a temporary DataFrame from the list of tuples
    temp_df = pd.DataFrame(adjusted_c_list, columns=['rlnCoordinateX', 'rlnCoordinateY'])
    temp_df['rlnImageName'] = [f"{i:05d}@{fname}.mrc" for i in range(len(temp_df))]
    temp_df['rlnMicrographName'] = fname + ".mrc"

    # If this is the first DataFrame, initialize df
    if idx == 0:
        df = temp_df
    else:
        # Append the temporary DataFrame to the existing df
        df = pd.concat([df, temp_df], ignore_index=True)

In [70]:
df

,rlnCoordinateX,rlnCoordinateY,rlnImageName,rlnMicrographName
0,2269.6,1031.0,00000@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
1,2232.8,3361.6,00001@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
2,2201.6,876.8,00002@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
3,2950.2,3084.6,00003@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
4,1365.0,3293.6,00004@Falcon_2012_06_12-14_33_35_0.mrc,Falcon_2012_06_12-14_33_35_0.mrc
...,...,...,...,...
49086,1468.0,3123.0,00486@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
49087,2853.0,1562.0,00487@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
49088,447.8,1599.0,00488@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
49089,1216.0,2367.0,00489@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc
49090,3903.0,3611.0,00490@Falcon_2012_06_13-03_06_44_0.mrc,Falcon_2012_06_13-03_06_44_0.mrc

In [71]:
starfile.write(df, f'{RESULT_DIR}/nms_particles.star')